AutoVentas/Models/Marca.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AutoVentas.Models
{
    public class Marca
    {

        [Key]
        public int IDMarca { get; set; }

        [Display(Name ="Nombre de la Marca"), Required(ErrorMessage ="El nombre de la marca es requerido.")]
        public String Nombre { get; set; }
    }
}

AutoVentas/Controllers/MarcaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoVentas.Models;

namespace AutoVentas.Controllers
{
    public class MarcaController : Controller
    {
        private DB_Carros db = new DB_Carros();

        // GET: Marca
        public ActionResult Index()
        {
            return View(db.Marca.ToList());
        }

        // GET: Marca/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marca.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // GET: Marca/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Marca/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDMarca,Nombre")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Marca.Add(marca);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(marca);
        }

        // GET: Marca/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marca.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDMarca,Nombre")] Marca marca)
        {
            if (ModelState.IsValid)
            {
                db.Entry(marca).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(marca);
        }

        // GET: Marca/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Marca marca = db.Marca.Find(id);
            if (marca == null)
            {
                return HttpNotFound();
            }
            return View(marca);
        }

        // POST: Marca/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Marca marca = db.Marca.Find(id);
            db.Marca.Remove(marca);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoVentas/Views/Marca/Create.cshtml
@model AutoVentas.Models.Marca

@{
    ViewBag.Title = "Registrar Marca";
}

<h2>Registra Marca</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingrese la informacion que se le solicita</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Marca", new { @class = "btn btn-primary btn-flat" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoVentas/Views/Marca/Delete.cshtml
@model AutoVentas.Models.Marca

@{
    ViewBag.Title = "Eliminar Marca";
}

<h2>Eliminar Marca</h2>

<h3 class="text-danger">Estas seguro de eliminar esta marca permanentemente?</h3>
<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index", "Marca", new { @class = "btn btn-primary btn-flat" })
        </div>
    }
</div>

AutoVentas/Views/Marca/Details.cshtml
@model AutoVentas.Models.Marca

@{
    ViewBag.Title = "Detalles de la Marca";
}

<h2>Detalles de la Marca</h2>

<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IDMarca }, new { @class = "btn btn-success btn-flat" }) |
    @Html.ActionLink("Regresar", "Index", "Marca", new { @class = "btn btn-primary btn-flat" })
</p>

AutoVentas/Views/Marca/Edit.cshtml
@model AutoVentas.Models.Marca

@{
    ViewBag.Title = "Editar Marca";
}

<h2>Editar Marca</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Informacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDMarca)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Marca", new { @class = "btn btn-primary btn-flat" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoVentas/Views/Marca/Index.cshtml
@model IEnumerable<AutoVentas.Models.Marca>

@{
    ViewBag.Title = "Marcas";
}

<h2>Marcas Registradas</h2>

<p>
    @Html.ActionLink("Registrar a una marca", "Create", "Marca", new { @class = "btn btn-primary btn-flat"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.IDMarca }, new { @class = "btn btn-success btn-flat" }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.IDMarca }, new { @class = "btn btn-primary btn-flat" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.IDMarca }, new { @class = "btn btn-danger btn-flat" })
        </td>
    </tr>
}

</table>