AutoVentas/Models/Vehiculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AutoVentas.Models
{
    public class Vehiculo
    {

        [Key]
        public int IDVehiculo { get; set; }

        [Display(Name = "Nombre")]
        public String Nombre { get; set; }
        
        public int IDMarca { get; set; }

        public virtual Marca Marca { get; set; }

        [Display(Name = "Modelo"), Required(ErrorMessage = "El modelo es requerido.")]
        public int Modelo { get; set; }

        [Display(Name = "Precio"), Required(ErrorMessage = "El precio es requerido.")]
        public double Precio { get;  set; }
        
        public String Estado { get; set; }

        public int IDTipoCombustible { get; set; }

        public virtual TipoCombustible TipoCombustible { get; set; }

        public int IDTipoVehiculo { get; set; }

        public virtual TipoVehiculo TipoVehiculo { get; set; }

        public virtual List<Archivo> Archivos { get; set; }
    }
}

AutoVentas/Controllers/VehiculoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoVentas.Models;
using System.Data.Entity.Infrastructure;

namespace AutoVentas.Controllers
{
    public class VehiculoController : Controller
    {
        private DB_Carros db = new DB_Carros();

        // GET: Vehiculo
        public ActionResult Index()
        {
            var vehiculo = db.Vehiculo.Include(v => v.Marca).Include(v => v.TipoCombustible).Include(v => v.TipoVehiculo);
            return View(vehiculo.ToList());
        }

        // GET: Vehiculo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // GET: Vehiculo/Create
        public ActionResult Create()
        {
            ViewBag.IDMarca = new SelectList(db.Marca, "IDMarca", "Nombre");
            ViewBag.IDTipoCombustible = new SelectList(db.TipoCombustible, "IDTipoCombustible", "Nombre");
            ViewBag.IDTipoVehiculo = new SelectList(db.TipoVehiculo, "IDTipoVehiculo", "Nombre");
            return View();
        }

        // POST: Vehiculo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Vehiculo vehiculo, HttpPostedFileBase archivo)
        {
            if (ModelState.IsValid)
            {
                if (archivo != null && archivo.ContentLength > 0)
                {
                    var image = new Archivo {
                            Nombre = System.IO.Path.GetFileName(archivo.FileName),
                            ContentType = archivo.ContentType
                    };
                    using (var reader = new System.IO.BinaryReader(archivo.InputStream))
                    {
                        image.Contenido = reader.ReadBytes(archivo.ContentLength);
                    };
                    vehiculo.Archivos = new List<Archivo> { image };
                }
                db.Vehiculo.Add(vehiculo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IDMarca = new SelectList(db.Marca, "IDMarca", "Nombre", vehiculo.IDMarca);
            ViewBag.IDTipoCombustible = new SelectList(db.TipoCombustible, "IDTipoCombustible", "Nombre", vehiculo.IDTipoCombustible);
            ViewBag.IDTipoVehiculo = new SelectList(db.TipoVehiculo, "IDTipoVehiculo", "Nombre", vehiculo.IDTipoVehiculo);
            return View(vehiculo);
        }

        // GET: Vehiculo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDMarca = new SelectList(db.Marca, "IDMarca", "Nombre", vehiculo.IDMarca);
            ViewBag.IDTipoCombustible = new SelectList(db.TipoCombustible, "IDTipoCombustible", "Nombre", vehiculo.IDTipoCombustible);
            ViewBag.IDTipoVehiculo = new SelectList(db.TipoVehiculo, "IDTipoVehiculo", "Nombre", vehiculo.IDTipoVehiculo);
            return View(vehiculo);
        }

        // POST: Vehiculo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, HttpPostedFileBase archivo)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vehiculo = db.Vehiculo.Find(id);
            if (TryUpdateModel(vehiculo, "", new String[] { "IDVehiculo, Nombre, IDMarca, Modelo, Precio, Estado, IDTipoCombustible, IDTipoVehiculo"}))
            {
                try
                {
                    if(archivo != null && archivo.ContentLength > 0)
                    {
                        db.Archivo.Remove(vehiculo.Archivos.First());
                        var imagen = new Archivo
                        {
                            Nombre = System.IO.Path.GetFileName(archivo.FileName),
                            ContentType = archivo.ContentType
                        };
                        using(var reader = new System.IO.BinaryReader(archivo.InputStream))
                        {
                            imagen.Contenido = reader.ReadBytes(archivo.ContentLength);
                        }
                        vehiculo.Archivos = new List<Archivo> { imagen };
                    }
                    db.Entry(vehiculo).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch(RetryLimitExceededException /* e */)
                {
                    ModelState.AddModelError("", "Error al actualizar los datos, por favor intentalo de nuevo.");
                }
            }
            ViewBag.IDMarca = new SelectList(db.Marca, "IDMarca", "Nombre", vehiculo.IDMarca);
            ViewBag.IDTipoCombustible = new SelectList(db.TipoCombustible, "IDTipoCombustible", "Nombre", vehiculo.IDTipoCombustible);
            ViewBag.IDTipoVehiculo = new SelectList(db.TipoVehiculo, "IDTipoVehiculo", "Nombre", vehiculo.IDTipoVehiculo);
            return View(vehiculo);
        }

        // GET: Vehiculo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            if (vehiculo == null)
            {
                return HttpNotFound();
            }
            return View(vehiculo);
        }

        // POST: Vehiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vehiculo vehiculo = db.Vehiculo.Find(id);
            db.Vehiculo.Remove(vehiculo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutoVentas/Views/Vehiculo/Create.cshtml
@model AutoVentas.Models.Vehiculo

@{
    ViewBag.Title = "Registrar Vehiculo";
}

<h2>Registrar Vehiculo</h2>


@using (Html.BeginForm("Create", "Vehiculo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingrese la informacion que se le solicita por favor.</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Marca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDMarca", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tipo de Combustible", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTipoCombustible", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTipoCombustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tipo Vehiculo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTipoVehiculo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTipoVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg, .png, .jpeg, .gif" id="archivo" name="archivo" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Vehiculo", new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutoVentas/Views/Vehiculo/Delete.cshtml
@model AutoVentas.Models.Vehiculo

@{
    ViewBag.Title = "Eliminar Vehiculo";
}

<h2>Eliminar Vehiculo</h2>

<h3 class="text-danger">Estas seguro que deseas eliminar este vehiculo permanemtemente?</h3>
<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Imagen
        </dt>
        <dd>
            <img src="~/Archivo/ObtenerArchivo?id=@Model.Archivos.FirstOrDefault().IDArchivo" alt="Imagen"
                 style="max-height: 200px; max-width: 200px; min-height: 200px; min-width: 200px;" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Marca.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVehiculo.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar", "Index", "Vehiculo", new { @class = "btn btn-primary" })
        </div>
    }
</div>

AutoVentas/Views/Vehiculo/Details.cshtml
@model AutoVentas.Models.Vehiculo

@{
    ViewBag.Title = "Detalles del vehiculo";
}

<h2>Detalles del Vehiculo</h2>

<div>
    <h4>Informacion</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Nombre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            Marca
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca.Nombre)
        </dd>

        <dt>
            Tipo de Combustible
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible.Nombre)
        </dd>

        <dt>
            Tipo de Vehiculo
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            Imagen
        </dt>
        <dd>
            <img src="~/Archivo/ObtenerArchivo?id=@Model.Archivos.FirstOrDefault().IDArchivo" alt="Imagen"
                 style="max-height: 200px; max-width: 200px; min-height: 200px; min-width: 200px;" />
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IDVehiculo }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Regresar", "Index", "Vehiculo", new { @class = "btn btn-primary" })
</p>

AutoVentas/Views/Vehiculo/Edit.cshtml
@model AutoVentas.Models.Vehiculo

@{
    ViewBag.Title = "Editar Vehiculo";
}

<h2>Editar Vehiculo</h2>

@using (Html.BeginForm("Edit", "Vehiculo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Informacion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDVehiculo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Marca", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDMarca", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDMarca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tipo Combustible", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTipoCombustible", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTipoCombustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Tipo Vehiculo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDTipoVehiculo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDTipoVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span class="control-label col-md-2"><strong>Imagen Actual</strong></span>
            <div class="col-md-10">
                <img src="~/Archivo/ObtenerArchivo?id=@Model.Archivos.FirstOrDefault().IDArchivo" alt="Imagen"
                     style="max-height: 200px; max-width: 200px; min-height: 200px; min-width: 200px;" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Foto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept=".jpg, .png, .jpeg, .gif" id="archivo" name="archivo" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index", "Vehiculo", new { @class = "btn btn-primary" })
</div>

AutoVentas/Views/Vehiculo/Index.cshtml
@model IEnumerable<AutoVentas.Models.Vehiculo>

@{
    ViewBag.Title = "Vehiculos Registrados";
}

<h2>Vehiculos Registrados</h2>

<p>
    @Html.ActionLink("Registrar un Vehiculo", "Create", "Vehiculo", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            Marca
        </th>
        <th>
            Tipo de Combustible
        </th>
        <th>
            Tipo de Vehiculo
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Marca.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoCombustible.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoVehiculo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IDVehiculo }, new { @class = "btn btn-success" }) |
            @Html.ActionLink("Detalles", "Details", new { id = item.IDVehiculo }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Eliminar", "Delete", new { id = item.IDVehiculo }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>